### ISSUE TITLE
Document difference between Ttodo and Todo.txt for completed tasks

### ISSUE THREAD

**Issue by schultzter** [tomtom/ttodo_vim#10]
There's a difference in the way Ttodo handles completed tasks and the Todo.txt standard, **I was just wondering why?** 

It's a bit confusing looking at the spec, but either the the priority should be discarded and moved to a `key:value` metadata; or it should be left between the `x` and the Completion date (2nd field). 

I personally prefer moving it to a metadata. 

I'm trying to understand your code - and learn Vim Script at the same time - to hopefully offer a patch for this. 

Thanks

Ttodo (priority left between dates):
```
x 2023-06-30 (C) 2023-06-21 Send invites for week of June 26 to team workshops @Context +Project
```

But according to Todo.txt it should either be (priority moved to metadata):
```
x 2023-06-30 2023-06-21 Send invites for week of June 26 to team workshops @Context +Project pri:C
```
or (priority stays in 2nd field):
```
x (C) 2023-06-30 2023-06-21 Send invites for week of June 26 to team workshops @Context +Project
```

See https://github.com/todotxt/todo.txt#rule-2-the-date-of-completion-appears-directly-after-the-x-separated-by-a-space and also https://github.com/todotxt/todo.txt#todotxt-format-rules

**Comment by tomtom** [comment]
Thank you very much for pointing this out. Maybe I implemented it this 
way because the SimpleTasks Android app does/did it this way. Maybe it 
hasn't been formalized yet when I wrote the respective function.

I will change it. Is there any tendency in the community as to which 
form is preferable?
