### ISSUE TITLE
Warning on start

### ISSUE THREAD

**Issue by SevereOverfl0w** [tomtom/ttodo_vim#7]
`tcomment: tcomment#DefineType() is deprecated; please use tcomment#type#Define() instead`

**Comment by tomtom** [comment]
Am 27.12.2018 um 23:07 schrieb Dominic Monroe:
> |tcomment: tcomment#DefineType() is deprecated; please use 
> tcomment#type#Define() instead|

Do you use tcomment#DefineType() in your local config? If so, you're 
asked to use tcomment#type#Define() instead as the alias 
tcomment#DefineType() will be removed sooner or later.

HTH

**Comment by SevereOverfl0w** [comment]
I think it is caused by https://github.com/tomtom/ttodo_vim/blob/81cd4083d5b245228a5c6b7edf89b4c5de212e66/autoload/tcomment/types/ttodo.vim

**Comment by tomtom** [comment]
Thanks. This should be fixed in 3b2b08147e2725c8f75ed292bca8e306b7814d39.
